## Configuration data
config = {
    "cvs_sites": [ 'ABINGTON',
                    'ACTON',
                    'AGAWAM',
                    'ALLSTON',
                    'AMHERST',
                    'ARLINGTON',
                    'ASHLAND',
                    'ATHOL',
                    'ATTLEBORO',
                    'BEDFORD',
                    'BELCHERTOWN',
                    'BELLINGHAM',
                    'BELMONT',
                    'BEVERLY',
                    'BILLERICA',
                    'BOSTON',
                    'BOURNE',
                    'BRAINTREE',
                    'BRIGHTON',
                    'BROCKTON',
                    'BROOKLINE',
                    'BURLINGTON',
                    'CAMBRIDGE',
                    'CANTON',
                    'CARVER',
                    'CHATHAM',
                    'CHELSEA',
                    'CHESTNUT HILL',
                    'CHICOPEE',
                    'COHASSET',
                    'CONCORD',
                    'DANVERS',
                    'DEDHAM',
                    'DORCHESTER',
                    'DRACUT',
                    'EAST BOSTON',
                    'EAST BRIDGEWATER',
                    'EAST FALMOUTH',
                    'EVERETT',
                    'FALL RIVER',
                    'FALMOUTH',
                    'FITCHBURG',
                    'FOXBOROUGH',
                    'FRAMINGHAM',
                    'GEORGETOWN',
                    'GLOUCESTER',
                    'GRANBY',
                    'GREAT BARRINGTON',
                    'GREENFIELD',
                    'HADLEY',
                    'HANOVER',
                    'HANSON',
                    'HARWICH',
                    'HARWICHPORT',
                    'HAVERHILL',
                    'HINGHAM',
                    'HOLBROOK',
                    'HOLLISTON',
                    'HOLYOKE',
                    'HOPKINTON',
                    'HUDSON',
                    'HYANNIS',
                    'HYDE PARK',
                    'IPSWICH',
                    'KINGSTON',
                    'LANESBOROUGH',
                    'LAWRENCE',
                    'LEOMINSTER',
                    'LEXINGTON',
                    'LONGMEADOW',
                    'LOWELL',
                    'LUNENBURG',
                    'LYNN',
                    'MALDEN',
                    'MARBLEHEAD',
                    'MARLBOROUGH',
                    'MASHPEE',
                    'MATTAPAN',
                    'MAYNARD',
                    'MEDFIELD',
                    'MEDFORD',
                    'METHUEN',
                    'MIDDLEBOROUGH',
                    'MIDDLETON',
                    'MILFORD',
                    'MILLBURY',
                    'MILLIS',
                    'NATICK',
                    'NEEDHAM',
                    'NEW BEDFORD',
                    'NEWBURYPORT',
                    'NEWTON',
                    'NORTH ANDOVER',
                    'NORTH ATTLEBOROUGH',
                    'NORTH BILLERICA',
                    'NORTH DARTMOUTH',
                    'NORTH EASTON',
                    'NORTH GRAFTON',
                    'NORTHAMPTON',
                    'NORWELL',
                    'ORLEANS',
                    'OXFORD',
                    'PALMER',
                    'PEABODY',
                    'PLAINVILLE',
                    'PLYMOUTH',
                    'PROVINCETOWN',
                    'QUINCY',
                    'RANDOLPH',
                    'READING',
                    'REVERE',
                    'ROSLINDALE',
                    'ROWLEY',
                    'SALEM',
                    'SALISBURY',
                    'SANDWICH',
                    'SAUGUS',
                    'SEEKONK',
                    'SHARON',
                    'SOMERVILLE',
                    'SOUTH EASTON',
                    'SOUTH HAMILTON',
                    'SOUTH WEYMOUTH',
                    'SOUTH YARMOUTH',
                    'SOUTHBRIDGE',
                    'SOUTHWICK',
                    'SPRINGFIELD',
                    'STONEHAM',
                    'STOUGHTON',
                    'STURBRIDGE',
                    'SWANSEA',
                    'TAUNTON',
                    'WALTHAM',
                    'WAREHAM',
                    'WATERTOWN',
                    'WAYLAND',
                    'WEBSTER',
                    'WELLESLEY',
                    'WEST BRIDGEWATER',
                    'WEST NEWTON',
                    'WEST SPRINGFIELD',
                    'WESTBOROUGH',
                    'WESTFIELD',
                    'WESTFORD',
                    'WESTPORT',
                    'WESTWOOD',
                    'WEYMOUTH',
                    'WILBRAHAM',
                    'WILMINGTON',
                    'WINCHENDON',
                    'WINCHESTER',
                    'WINTHROP',
                    'WOBURN',
                    'WOLLASTON',
                    'WORCESTER',
                    'WRENTHAM'
                ]
}
